#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# promptmessages 0.1
#
# Alexander F Rødseth <xyproto@archlinux.org>
# 2017-10-05
#
# MIT licensed
#

import os
import os.path
import datetime

dir_path = os.path.dirname(os.path.realpath(__file__))
time_conf = os.path.join(dir_path, "time.conf")


class Event:

    def __init__(self, start_hour, start_minute, end_hour, end_minute, desc):
        self.start_hour = int(start_hour)
        self.start_minute = int(start_minute)
        self.end_hour = int(end_hour)
        self.end_minute = int(end_minute)
        self.desc = desc.strip()

    def __str__(self):
        return "{}:{} - {}:{} : {}".format(self.start_hour, self.start_minute, self.end_hour, self.end_minute, self.desc)

    def at(self, hour, minute):
        start = self.start_hour * 60 + self.start_minute
        end = self.end_hour * 60 + self.end_minute
        given = hour * 60 + minute
        return given >= start and given <= end


def main():
    # List of events
    events = []

    lines = open(time_conf).read().split("\n")[:-1]
    for line in lines:
        if line.strip().startswith("#"):
            continue
        if line.count(":") >= 2 and line.count("-") >= 1:
            elements = line.split("-")
            if len(elements) == 2:
                start_hour, start_minute = elements[0].split(":", 1)
                end_hour, end_minute, desc = elements[1].split(":", 2)
                events.append(Event(start_hour, start_minute, end_hour, end_minute, desc))

    now = datetime.datetime.now()
    for event in events:
        if event.at(now.hour, now.minute):
            print(event.desc)


if __name__ == "__main__":
    main()
