#!/bin/bash

SOURCE_DIR=$(dirname "$0")
DESTDIR="$1"
PREFIX="$DESTDIR${2:-/usr}"
SYS_DIR=$PREFIX/share/prem
BIN_DIR=$PREFIX/bin

# msg outputs a topic + green message, with a final newline
msg() {
  local topic="$1"
  shift
  if [ ! -z "$*" ]; then
    printf "%b" "* \e[1;37m[\e[0m\e[1;34m$topic\e[0m\e[1;37m]"
    printf ' %.0s' $(seq ${#topic} 10)
    printf "%b\n" "\e[0;32m$*\e[0m"
  fi
}

main() {
  # Check if the file already exists
  if [ -x "$BIN_DIR/prem" ]; then
    # Only upgrade the executable if the files differ
    diff -q "$SOURCE_DIR/prem" "$BIN_DIR/prem" 2>&1 1>/dev/null && msg prem 'Already in place' || (msg prem "Installing to $BIN_DIR/prem"; install -Dm755 "$SOURCE_DIR/prem" "$BIN_DIR/prem")
  else
    msg prem "Installing to $BIN_DIR/prem"
    install -Dm755 "$SOURCE_DIR/prem" "$BIN_DIR/prem"
  fi

  # Check if the file already exists
  if [ -x "$BIN_DIR/prem-setup" ]; then
    # Only upgrade the executable if the files differ
    diff -q "$SOURCE_DIR/prem-setup" "$BIN_DIR/prem-setup" 2>&1 1>/dev/null && msg prem 'Already in place' || (msg prem "Installing to $BIN_DIR/prem-setup"; install -Dm755 "$SOURCE_DIR/prem-setup" "$BIN_DIR/prem-setup")
  else
    msg prem "Installing to $BIN_DIR/prem-setup"
    install -Dm755 "$SOURCE_DIR/prem-setup" "$BIN_DIR/prem-setup"
  fi

  # Install to $SYS_DIR/time.conf
  if [ ! -f $SYS_DIR/time.example.conf ]; then
    msg 'time.conf' "Installing to $SYS_DIR_DIR/time.example.conf"
    install -Dm644 "$SOURCE_DIR/time.example.conf" "$SYS_DIR/time.example.conf"
  else
    msg 'time.conf' "Already in place"
  fi
}

main
